public with sharing class Constants {
   
    //for check dock type
    public static final String CONTROLLED_DOC_TYPE = 'Controlled%20Documents';
    public static final String GENERAL_DOC_TYPE = 'General%20Documents';
    public static final String LOCKED_DOC_TYPE = 'Locked%20Documents';

    
    public static final String SPLIT_BY_DOT = '\\.';

    public static final String EXTERNAL_DOC_INFO_ID = 'item:L3NpdGVzL2VkbXNjbGllbnRkb2Nz:6f4ce06a-eob6-4a22-8710-c3e42f39bfd4:';
    public static final String EDMS_PATH = '/sites/edmsclientdocs/';



   //for check type of fields in SharePoint
   public static final String CHOICE_TYPE = 'Choice';
   public static final String NUMBER_TYPE = 'Number';
   public static final String TEXT_TYPE = 'Text';
   public static final String BOOLEAN_TYPE = 'Boolean';
   public static final String URL_TYPE = 'URL';
   public static final String FILE_TYPE = 'File';
   public static final String GUID_TYPE = 'Guid';
   public static final String NOTE_TYPE = 'Note';

}
