public with sharing class Constants {
   
    public static final String CONTROLLED_DOC_TYPE = 'Controlled%20Documents';
    public static final String GENERAL_DOC_TYPE = 'General%20Documents';
    public static final String LOCKED_DOC_TYPE = 'Locked%20Documents';

    
    public static final String SPLIT_BY_DOT = '\\.';

    public static final String EXTERNAL_DOC_INFO_ID = 'item:L3NpdGVzL2VkbXNjbGllbnRkb2Nz:6f4ce06a-eob6-4a22-8710-c3e42f39bfd4:';

}
